server:
  port: 8089
  error:
    include-message: always

logging:
  level:
    org.springframework: INFO
    com.mkyong: DEBUG
    jdbc: DEBUG

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: "ALWAYS"
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true

features:
  canaryflag: true
  datastream: true
  dbdata: true
  messaging: false

spring:
  application:
    name: accounts-application
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: ${management.server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
        tags: env=dev
        serviceName: dev-${spring.application.name}
    config:
      enabled: false
  profiles:
    active: dev
  main:
    banner-mode: log
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: update
  # datasource:
  #   url: jdbc:mysql://localhost:3306/usersdb
  #   username: "dbuser@localhost"
  #   password: "localpass"
  #   hikari:
  #     data-source-properties:
  #       serverTimezone: "GMT"
  #       useSSL: false
# In memory DB - for dbdata flag set to false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

#custom properties
info:
  app:
    name: accounts-application
    description: Spring Demo application
  author: 
    name: "Stefan Monko"
    mail: "stefan@stefanmonko.sk / monkos@posam.sk"